[project]
name = "dns-magnitude-dashboard"
version = "1.0.0"
description = "DNS Magnitude Web Dashboard"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.0.0",
    "pandas>=2.0.0",
]

[tool.uv]
dev-dependencies = []
