[project]
name = "dns-magnitude-analysis"
version = "1.0.0"
description = "DNS Magnitude Analysis Tools"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
]

[tool.uv]
dev-dependencies = []
